CREATE TABLE IF NOT EXISTS propertybox.property_listing (
    record_id SERIAL PRIMARY KEY,
    property_id TEXT,
    currency VARCHAR(10) NOT NULL,
    listing_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20),
    
     rental_or_sell TEXT,
  property_category TEXT,
  property_type TEXT,
  possession_status TEXT,
  price NUMERIC,
  location TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  facing TEXT,
  size TEXT,
  furnished TEXT,
  number_of_floors NUMERIC,
  bed_rooms TEXT,
  bath_rooms TEXT,
  car_park TEXT,
  extra_room TEXT,
  initial_likes INTEGER,
  is_available BOOLEAN,
  amenities TEXT[], -- Array of strings
  image1 TEXT,
  image2 TEXT,
  image3 TEXT,
  image4 TEXT,
  position JSONB, -- For dynamic data
  doc1 TEXT,
  doc2 TEXT,
  doc3 TEXT,
  doc4 TEXT,
  doc1_name TEXT,
  doc2_name TEXT,
  doc3_name TEXT,
  doc4_name TEXT,
  video1 TEXT,
  hand_over TEXT,
  box_enabled BOOLEAN,
  doc_id TEXT UNIQUE,
  rental_income NUMERIC,
  user_id TEXT,
  timestamp TIMESTAMPTZ,
  user_details JSONB, -- Assuming you serialize UserModel
  listing_type TEXT,
  total_portion NUMERIC,
  flat_floors NUMERIC,
  distance_from_user TEXT,
  property_box_timestamp TIMESTAMPTZ,
  is_view_listing BOOLEAN,
  images_or_videos TEXT,
  price_per_size NUMERIC,
  other_price NUMERIC,
  amenities_price NUMERIC,
  description TEXT,
  image5 TEXT,
  image6 TEXT,
  image7 TEXT,
  image8 TEXT,
  image9 TEXT,
  image10 TEXT,
  brochure TEXT,
  age TEXT

);